Repository AY2021S1-CS2103-W14-3/tp, pull requests merged in 2020-10, with the labels that each got.

#44 Update and fix data in tests and json
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/data/JsonAddressBookStorageTest/invalidExpenseLedger.json
  src/test/data/JsonSerializableAddressBookTest/typicalExpensesLedger.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditExpenseDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/expense/ExpenseTest.java
  src/test/java/seedu/address/model/expense/UniqueExpenseListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedExpenseTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/ExpenseBuilder.java
  src/test/java/seedu/address/testutil/TypicalExpenses.java
Labels: type.Task

#50 Add GUI for budget balance
  src/main/java/seedu/address/ui/BudgetDisplay.java
  src/main/resources/view/BudgetDisplay.fxml
  src/main/resources/view/DarkTheme.css
Labels: type.Task

#51 Merge branch-list-budget into master
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/expense/UniqueExpenseList.java
  src/main/java/seedu/address/ui/BudgetDisplay.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/BudgetDisplay.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: type.Story, type.Task

#48 Update User Guide to v1.2
  docs/UserGuide.md
  docs/images/ug_example/add_example.PNG
  docs/images/ug_example/delete_example.PNG
  docs/images/ug_example/edit_example.PNG
  docs/images/ug_example/find_example.PNG
  docs/images/ug_example/list_example.PNG
  docs/images/ug_example/remark_example.PNG
  docs/images/ug_example/topup_example.PNG
Labels: type.Task

#54 Update Use Cases in Developer Guide
  docs/DeveloperGuide.md
Labels: priority.High, type.Task

#62 Fixed Bug in TopupCommandParser
  src/main/java/seedu/expense/logic/parser/TopupCommandParser.java
Labels: bug

#86 Add sort command
  src/main/java/seedu/expense/logic/commands/SortCommand.java
  src/main/java/seedu/expense/logic/parser/CliSyntax.java
  src/main/java/seedu/expense/logic/parser/ExpenseBookParser.java
  src/main/java/seedu/expense/logic/parser/SortCommandParser.java
  src/main/java/seedu/expense/model/ExpenseBook.java
  src/main/java/seedu/expense/model/Model.java
  src/main/java/seedu/expense/model/ModelManager.java
  src/main/java/seedu/expense/model/expense/AmountComparator.java
  src/main/java/seedu/expense/model/expense/Date.java
  src/main/java/seedu/expense/model/expense/DateComparator.java
  src/main/java/seedu/expense/model/expense/DescriptionComparator.java
  src/main/java/seedu/expense/model/expense/SortKeyComparator.java
  src/main/java/seedu/expense/model/expense/UniqueExpenseList.java
  src/test/java/seedu/expense/logic/commands/AddCategoryCommandTest.java
  src/test/java/seedu/expense/logic/commands/AddCommandTest.java
  src/test/java/seedu/expense/logic/commands/DeleteCategoryCommandTest.java
  src/test/java/seedu/expense/logic/commands/SortCommandTest.java
  src/test/java/seedu/expense/logic/commands/SwitchCommandTest.java
  src/test/java/seedu/expense/logic/commands/TopupCommandTest.java
  src/test/java/seedu/expense/logic/parser/SortCommandParserTest.java
Labels: priority.High, type.Story

#97 Update Developer Guide for v1.3
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/SortSequenceDiagram1.puml
  docs/diagrams/SortSequenceDiagram2.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/SortSequenceDiagram1.png
  docs/images/SortSequenceDiagram2.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation

#100 Update UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/ug_example/addCat_example.PNG
  docs/images/ug_example/addCat_example_2.PNG
  docs/images/ug_example/add_example.PNG
  docs/images/ug_example/alias_example.PNG
  docs/images/ug_example/alias_example_2.PNG
  docs/images/ug_example/deleteCat_example.PNG
  docs/images/ug_example/delete_example.PNG
  docs/images/ug_example/edit_example.PNG
  docs/images/ug_example/find_example.PNG
  docs/images/ug_example/find_example_2.PNG
  docs/images/ug_example/list_example.PNG
  docs/images/ug_example/remark_example.PNG
  docs/images/ug_example/sort_example.PNG
  docs/images/ug_example/sort_example_2.PNG
  docs/images/ug_example/sort_example_3.PNG
  docs/images/ug_example/sort_example_4.PNG
  docs/images/ug_example/switch_example.PNG
  docs/images/ug_example/topup_example.PNG
  src/main/java/seedu/expense/logic/commands/SortCommand.java
  src/main/java/seedu/expense/logic/parser/SortCommandParser.java
Labels: documentation
