Repository AY2021S1-CS2103-W14-3/tp, pull requests merged in 2020-11, with the labels that each got.

#151 Update CategoryNotFoundException and Expense Equality
  src/main/java/seedu/expense/commons/core/Messages.java
  src/main/java/seedu/expense/logic/commands/AddCategoryCommand.java
  src/main/java/seedu/expense/logic/commands/AddCommand.java
  src/main/java/seedu/expense/logic/commands/AliasCommand.java
  src/main/java/seedu/expense/logic/commands/ClearCommand.java
  src/main/java/seedu/expense/logic/commands/DeleteCategoryCommand.java
  src/main/java/seedu/expense/logic/commands/DeleteCommand.java
  src/main/java/seedu/expense/logic/commands/EditCommand.java
  src/main/java/seedu/expense/logic/commands/ExitCommand.java
  src/main/java/seedu/expense/logic/commands/HelpCommand.java
  src/main/java/seedu/expense/logic/commands/ListCommand.java
  src/main/java/seedu/expense/logic/commands/RemarkCommand.java
  src/main/java/seedu/expense/logic/commands/SortCommand.java
  src/main/java/seedu/expense/logic/commands/SwitchCommand.java
  src/main/java/seedu/expense/logic/commands/TopupCommand.java
  src/main/java/seedu/expense/model/ExpenseBook.java
  src/main/java/seedu/expense/model/ModelManager.java
  src/main/java/seedu/expense/model/expense/Expense.java
  src/main/java/seedu/expense/model/expense/exceptions/CategoryNotFoundException.java
  src/main/java/seedu/expense/storage/JsonSerializableExpenseBook.java
  src/test/data/JsonSerializableExpenseBookTest/duplicateExpenseLedger.json
  src/test/java/seedu/expense/logic/LogicManagerTest.java
  src/test/java/seedu/expense/logic/commands/AliasCommandTest.java
  src/test/java/seedu/expense/logic/commands/DeleteCategoryCommandTest.java
  src/test/java/seedu/expense/model/ExpenseBookTest.java
  src/test/java/seedu/expense/model/ModelManagerTest.java
  src/test/java/seedu/expense/model/expense/ExpenseTest.java
  src/test/java/seedu/expense/testutil/ExpenseBookBuilder.java
Labels: bug, priority.High

#150 Change Amount datatype to BigDecimal, Fix DescriptionComparator
  src/main/java/seedu/expense/logic/commands/TopupCommand.java
  src/main/java/seedu/expense/model/ExpenseBook.java
  src/main/java/seedu/expense/model/Statistics.java
  src/main/java/seedu/expense/model/budget/CategoryBudget.java
  src/main/java/seedu/expense/model/budget/UniqueCategoryBudgetList.java
  src/main/java/seedu/expense/model/expense/Amount.java
  src/main/java/seedu/expense/model/expense/AmountComparator.java
  src/main/java/seedu/expense/model/expense/DescriptionComparator.java
  src/main/java/seedu/expense/model/expense/UniqueExpenseList.java
  src/main/java/seedu/expense/ui/BudgetDisplay.java
  src/test/java/seedu/expense/logic/commands/TopupCommandTest.java
  src/test/java/seedu/expense/model/ExpenseBookTest.java
  src/test/java/seedu/expense/model/expense/AmountTest.java
Labels: bug, priority.High

#157 Fix rounding error in Amount causing problems in BudgetDisplay
  src/main/java/seedu/expense/model/expense/Amount.java
  src/main/java/seedu/expense/ui/BudgetDisplay.java
Labels: bug

#170 Update various class diagrams in DG
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation

#152 Fix typos and bugs with UG, update UG
  docs/UserGuide.md
  docs/images/ug_example/clear_example.png
  docs/images/ug_example/find_example.PNG
  src/main/java/seedu/expense/commons/core/Messages.java
  src/main/java/seedu/expense/logic/commands/AddCategoryCommand.java
  src/main/java/seedu/expense/logic/commands/AddCommand.java
  src/main/java/seedu/expense/logic/commands/DeleteCategoryCommand.java
  src/main/java/seedu/expense/logic/commands/EditCommand.java
  src/main/java/seedu/expense/logic/commands/ReduceCommand.java
  src/main/java/seedu/expense/logic/commands/SwitchCommand.java
Labels: documentation

#172 Fix Amount Range issue with Minterm and Add check for total sum
  src/main/java/seedu/expense/logic/commands/AddCommand.java
  src/main/java/seedu/expense/logic/commands/EditCommand.java
  src/main/java/seedu/expense/logic/commands/TopupCommand.java
  src/main/java/seedu/expense/model/Model.java
  src/main/java/seedu/expense/model/ModelManager.java
  src/main/java/seedu/expense/model/expense/Amount.java
  src/test/java/seedu/expense/logic/commands/AddCategoryCommandTest.java
  src/test/java/seedu/expense/logic/commands/AddCommandTest.java
  src/test/java/seedu/expense/logic/commands/AliasCommandTest.java
  src/test/java/seedu/expense/logic/commands/DeleteCategoryCommandTest.java
  src/test/java/seedu/expense/logic/commands/EditCommandTest.java
  src/test/java/seedu/expense/logic/commands/ReduceCommandTest.java
  src/test/java/seedu/expense/logic/commands/ResetAliasCommandTest.java
  src/test/java/seedu/expense/logic/commands/SwitchCommandTest.java
  src/test/java/seedu/expense/logic/commands/TopupCommandTest.java
Labels: bug
